name: Release
on: [push, pull_request]

jobs:
  # unit-tests:
  #   runs-on: windows-latest
  #   timeout-minutes: 5

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: recursive
  #         token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Install Roblox Studio
  #       uses: osyrisrblx/roblox-win-installer-action@master
  #       with:
  #         cookie: ${{ secrets.ROBLOSECURITY }}
  #         token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Setup Toolchain
  #       uses: Roblox/setup-foreman@v1
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Build Test Project
  #       run: rojo build test.project.json -o scripts/testplace.rbxlx

  #     - name: Run Unit Tests
  #       run: run-in-roblox --place scripts/testplace.rbxlx --script scripts/run-tests.server.lua

  release:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[release]')
    # needs: [unit-tests]
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Toolchain
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Project Details
        run: |
          PROJECT_NAME=`grep -Po '(?<=^name = ")([^"]+)' rotriever.toml`
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          PROJECT_VERSION=`grep -Po '(?<=^version = ")([^"]+)' rotriever.toml`
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
          PROJECT_ASSET_ID=`grep -Po '(?<=^assetId = ")([^"]+)' rotriever.toml`
          echo "PROJECT_ASSET_ID=$PROJECT_ASSET_ID" >> $GITHUB_ENV

      - name: Build Project
        run: |
          rojo build default.project.json -o dist/${{ env.PROJECT_NAME }}.rbxmx
          rojo build default.project.json -o dist/${{ env.PROJECT_NAME }}.rbxm

      - name: Upload to Roblox
        run: rojo upload default.project.json --asset_id ${{ env.PROJECT_ASSET_ID }} --cookie ${{ secrets.ROBLOSECURITY }}

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-releases@v1
        with:
          name: ${{ env.PROJECT_VERSION }}
          tag_name: ${{ env.PROJECT_VERSION }}
          files: |
            dist/${{ env.PROJECT_NAME }}.rbxmx
            dist/${{ env.PROJECT_NAME }}.rbxm
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
